name: Chambers Salon
favicon: null
layout_spectrum: 0.98451
typography_spectrum: 0.9015679159201682
title: Chambers Salon - Style and colour
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c4c4c4'
    - '#f7e6d4'
    - '#8e8e8e'
    - '#85afa3'
  brandStrength: 0.25
  lightness: 0.7130910891573876
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
